name: "garmin_training_log"
version: "1.0.0"
config-version: 2

profile: "garmin_training_log"

model-paths: ["models"]

target-path: "target"
clean-targets: ["target", "dbt_packages"]

vars:
  landing_root: "../astro/include/data/landing"
  lookback_days: 0

models:
  garmin_training_log:
    +materialized: view
    bronze:
      +schema: bronze
    silver:
      +schema: silver
    gold:
      +schema: gold
