name: "garmin_training_log"
version: "1.0.0"
config-version: 2

profile: "garmin_training_log"

model-paths: ["models"]

target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  garmin_training_log:
    +materialized: view
    silver:
      +schema: silver
