[project]
name = "garmin-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dbt-core>=1.11.8",
    "dbt-duckdb>=1.10.1",
    "duckdb>=1.5.1",
    "fastapi>=0.117.1",
    "garminconnect==0.3.2",
    "pandera>=0.30.1",
    "polars>=1.39.3",
    "python-dotenv>=1.2.1",
    "requests>=2.32.5",
    "streamlit>=1.56.0",
    "uvicorn>=0.41.0",
]

[project.optional-dependencies]
airflow-tests = [
    "apache-airflow>=3.1.0,<3.2.0",
    "pytest>=8.0.0",
    "ruff>=0.9.0",
]

dev = [
    "sqlfluff",
    "sqlfluff-templater-dbt",
]
