"""add session summary fields

Revision ID: a1ce721fe649
Revises: 7e5425a590e8
Create Date: 2026-05-07 23:37:32.264248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1ce721fe649'
down_revision: Union[str, Sequence[str], None] = '7e5425a590e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_sessions', sa.Column('summary', sa.Text(), nullable=True))
    op.add_column('chat_sessions', sa.Column('summarized_message_count', sa.Integer(), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_sessions', 'summarized_message_count')
    op.drop_column('chat_sessions', 'summary')
    # ### end Alembic commands ###
