pipelines:
  garmin_ingest:
    storage_root: include/data/raw/garmin
    activities_folder: activities
    assets:
      - key: splits
        enabled: true
        output_folder: splits
        overwrite: true
      - key: activity_details
        enabled: true
        output_folder: activity_details
        overwrite: true
  raw_to_landing:
    source_path: include/data/raw/garmin
    landing_path: include/data/landing
    quarantine_dir: include/data/quarantine
    assets:
      activities:
        enabled: true
        source_folder: activities
        extract:
          payload_kind: list
        target_table: activities
        column_mapping:
          - target: activity_id
            source: activityId
            dtype: int64
            required: true
          - target: start_time_local
            source: startTimeLocal
            dtype: string
            required: true
          - target: start_time_gmt
            source: startTimeGMT
            dtype: string
            required: true
          - target: activity_name
            source: activityName
            dtype: string
            required: false
          - target: activity_type
            source: activityType.typeKey
            dtype: string
            required: true
          - target: distance
            source: distance
            dtype: float64
            required: true
          - target: duration
            source: duration
            dtype: float64
            required: true
          - target: owner_id
            source: ownerId
            dtype: int64
            required: false
          - target: owner_full_name
            source: ownerFullName
            dtype: string
            required: false
          - target: average_speed
            source: averageSpeed
            dtype: float64
            required: false
          - target: average_hr
            source: averageHR
            dtype: float64
            required: false
          - target: has_splits
            source: hasSplits
            dtype: boolean
            required: false
          - target: device_id
            source: deviceId
            dtype: int64
            required: false
      splits:
        enabled: true
        source_folder: splits
        extract:
          payload_kind: object
          records_path: lapDTOs
          context_key:
            source:  activityId
            target: activity_id
        target_table: splits
        column_mapping:
          - target: activity_id
            source: activityId
            dtype: int64
            required: true
          - target: start_time_gmt
            source: startTimeGMT
            dtype: string
            required: true
          - target: intensity_type
            source: intensityType
            dtype: string
            required: false
          - target: distance
            source: distance
            dtype: float64
            required: true
          - target: duration
            source: duration
            dtype: float64
            required: true
          - target: average_speed
            source: averageSpeed
            dtype: float64
            required: false
          - target: average_hr
            source: averageHR
            dtype: float64
            required: false
          - target: max_hr
            source: maxHR
            dtype: float64
            required: false
          - target: message_index
            source: messageIndex
            dtype: int64
            required: false
          - target: workout_step_index
            source: wktStepIndex
            dtype: int64
            required: false
      activity_details:
        enabled: true
        source_folder: activity_details
        extract:
          payload_kind: descriptor_metrics
          schema_path: metricDescriptors
          schema_index_field: metricsIndex
          schema_key_field: key
          schema_unit_path: unit
          records_path: activityDetailMetrics
          values_path: metrics
          context_key:
            source: activityId
            target: activity_id
        target_table: activity_details
        column_mapping:
          - { target: activity_id, source: activity_id, dtype: int64, required: true }
          - { target: measurement_index, source: measurement_index, dtype: int64, required: true }
          - { target: metric_index, source: metric_index, dtype: int64, required: true }
          - { target: metric_key, source: metric_key, dtype: string, required: true }
          - { target: metric_value, source: metric_value, dtype: float64, required: false }
          - { target: unit_key, source: unit_key, dtype: string, required: false }
          - { target: unit_factor, source: unit_factor, dtype: float64, required: false }
